@aresu_txt_editor_backend_HostAddress = http://localhost:5129

###

POST {{aresu_txt_editor_backend_HostAddress}}/user/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "Test@1234"
}

###
POST {{aresu_txt_editor_backend_HostAddress}}/user/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "Test@1234"
}

### Document Endpoints

### Get all documents
GET {{aresu_txt_editor_backend_HostAddress}}/document

### Create a new document
POST {{aresu_txt_editor_backend_HostAddress}}/document
Content-Type: application/json

{
  "title": "My First Document"
}