public enum DocumentLockOpResult
{
    SUCCESS,
    DOCUMENT_ALREADY_OCCUPIED,
    INVALID_SESSION_ID,
    SESSION_ID_OWNER_DOES_NOT_MATCH,
    DOCUMENT_UNOCCUPIED,
    DOCUMENT_NOT_OCCUPIED_BY_SESSION,
}